Initial rewrite to bash

diff --git a/txssh b/txssh
--- a/txssh
+++ b/txssh
@@ -1,11 +1,12 @@
+#!/usr/bin/bash
 
-### txssh --- light cssh implementation using zsh and tmux
+### txssh --- light cssh implementation using bash and tmux
 
-## Copyright (c) 2013-2014 Zachary Elliott
+## Copyright (c) 2013-2015 Zachary Elliott
 ##
-## Authors: Zachary Elliott <zach@nyu.edu>
-## URL: https://github.com/zellio/zsh-config/blob/master/functions/txssh
-## Version: 0.1.3
+## Authors: Zachary Elliott <contact@zell.io>
+## URL: https://github.com/zellio/txssh
+## Version: 0.2.0
 
 ### Commentary:
 
@@ -23,9 +24,7 @@
 ## Software is furnished to do so, subject to the following conditions:
 
 ## The above copyright notice and this permission notice shall be included in
-## all copies or substantial portions of the Software, and that the name of
-## NYU not be used in advertising or publicity pertaining to distribution of
-## the software without specific written permission.
+## all copies or substantial portions of the Software.
 
 ## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
@@ -37,17 +36,38 @@
 
 ### Code:
 
-local VERSION=0.1.3 basename=$(\basename $0)
+function error
+{
+	echo -e "\e[1;31m>>> ERROR: $@\e[0m"
+	return 1
+}
 
-usage() {
-    \cat <<EOF
-Usage: ${basename} [OPTION]... [HOST]...
+function requires
+{
+	if ! command -v "$1" >/dev/null 2>&1; then
+		error "Required program \`$1' not found in \$PATH"
+		exit 1
+	fi
+
+	return 0
+}
+
+requires basename
+requires ssh
+requires tmux
+
+tx__basename="$(basename "$0")"
+
+function tx__usage
+{
+	cat <<EOF
+Usage: $tx__basename [OPTION]... [HOST]...
 
 Specific options:
     -a, --action HOST                Command to run in foreign shell
     -o, --options OPTIONS            String of options for ssh
     -p, --port PORT                  Default port number
-    -s, --session NAME               Tmux session name (${basename})
+    -s, --session NAME               Tmux session name ($tx__basename)
     -t, --title TITLE                Title header for tmux frames
     -u, --user USERNAME              Default foreign username
 
@@ -56,113 +76,134 @@ General options:
     -h, --help                       Display this help message.
         --version                    Display the version number
 
-${basename} home page: <https://github.com/zellio/zsh-config>
-Report bugs to: <https://github.com/zellio/zsh-config/issues>
+$tx__basename home page: <https://github.com/zellio/txssh>
+Report bugs to: <https://github.com/zellio/txssh>
 
 EOF
 }
 
-version() {
-    \cat <<EOF
-${VERSION}
+function version
+{
+	cat <<EOF
+0.2.0
 EOF
 }
 
-error() {
-    \echo -n "$fg_bold[red]>>> ERROR: "
-    \echo -n $1
-    \echo "$reset_color"
+function tx__main
+{
+	ARGS=$(getopt \
+			   --longoptions 'action:,options:,port:,session:,title:,user:,debug,help,version' \
+			   --name "$tx__basename" \
+			   --options 'a:o:p:s:t:u:h' \
+			   -- "$@")
+
+	if (( $? )); then
+		tx__usage
+		return 1
+	fi
+
+	eval set -- "$ARGS"
+
+	local action=
+	local -a options
+	local port=
+	local session="$tx__basename"
+	local title=
+	local user=
+
+	while :; do
+		case "$1" in
+			-a|--action)
+				action="$2"
+				shift 2
+				;;
+			-o|--options)
+				options+=("$2")
+				shift 2
+				;;
+			-p|--port)
+				port="$2"
+				shift 2
+				;;
+			-s|--session)
+				session="$2"
+				shift 2
+				;;
+			-t|--title)
+				title="$2"
+				shift 2
+				;;
+			-u|--user)
+				user="$2"
+				shift 2
+				;;
+
+			--debug)
+				set -x
+				shift 1
+				;;
+			-h|--help)
+				tx__usage
+				return 0
+				;;
+			--version)
+				tx__version
+				return 0
+				;;
+
+			--)
+				shift 1
+				break
+				;;
+		esac
+	done
+
+	if tmux has-session -t "$session_name" 2>/dev/null; then
+		error "Session \`$session' already exists"
+		return 1
+	fi
+
+	local -a hosts
+	hosts=("$@")
+
+	if [ "${#hosts[@]}" -eq 0 ]; then
+		error "No hosts provided"
+		return 1
+	fi
+
+	local ssh_cmd="$(command -v ssh)"
+
+	if [ -n "$user" ]; then
+		ssh_cmd+=" -l $user"
+	fi
+
+	if [ -n "$port" ]; then
+		ssh_cmd+=" -p $port"
+	fi
+
+	if [ "${#options[@]}" -ne 0 ]; then
+		ssh_cmd+="$(printf -- " -o %s" "${options[@]}")"
+	fi
+
+	tmux new-session -d -s "$session"
+	for host in "${hosts[@]}"; do
+		tmux split-window -t "$session" "$ssh_cmd $host $action"
+	done
+
+	local window="$(tmux lsw -t "$session" | cut -d: -f1)"
+	local pane="$(tmux lsp -t "$session:$window" | head -n1 | cut -d: -f1)"
+
+	tmux kill-pane -t "$session:$window.$pane"
+
+	tmux set-window-option -t "$session" synchronize-panes on
+	tmux select-layout -t "$session" tiled
+	tmux attach-session -t "$session"
+
+	return 0
 }
 
-# Sanity check for the existance of tmux
+tx__main "$@"
 
-if [[ -z "$(command -v tmux)" ]]; then
-    error "program tmux not found. tmux require for ${basename}"
-    return 1
-fi
+exit $?
 
-# Handle no args
-[[ -z "$@" ]] && { usage; return 0; }
-
-
-# Run zparseopts to extrace command flags
-#  - Everything left over is considered to be a hostname
-
-local -A options
-local -a debug help version action user port opts title session new_session
-zparseopts -D -A options \
-    d=debug -debug=debug \
-    h=help -help=help \
-    -version=version \
-    a:=action -action:=action \
-    u:=user -user:=user \
-    p:=port -port:=port \
-    o:=opts -options:=opts \
-    t:=title -title:=title \
-    s:=session -session:=session
-    # n:=new_session -new-session=new_session
-
-
-# Set debug before anything else
-
-[[ -n "$debug" ]] && setopt xtrace
-
-# Run help and version with prejudice
-
-[[ -n "$help" ]] && { usage; return 0; }
-[[ -n "$version" ]] && { version; return 0; }
-
-local session_name=${options[--session]:=${options[-s]:=${basename}}}
-
-local session_exists=$(\tmux ls -F "#{session_name}" 2> /dev/null |
-    \grep -P "^${session_name}$")
-
-# Possibly add a flag to overrule this
-
-if [[ -n "$session_exists" ]]; then
-    error "session \"${session_name}\" already exists";
-    return 1
-fi
-
-typeset -a hosts
-hosts=( "$@" )
-
-if [ -z "$hosts" ]; then
-    error "no hosts provided"
-    return 1
-fi
-
-local ssh_cmd="$(command -v ssh)"
-
-if [ -n "$user" ]; then
-    user=${options[--user]:=$options[-u]}
-    ssh_cmd="$ssh_cmd -l $user"
-fi
-
-if [ -n "$port" ]; then
-    port=${options[--port]:=$options[-p]}
-    ssh_cmd="$ssh_cmd -p $port"
-fi
-
-if [ -n "$action" ]; then
-    action=${options[--action]:=$options[-a]}
-fi
-
-if [ -n "$opts" ]; then
-    opts=${options[--options]:=$options[-o]}
-    ssh_cmd="$ssh_cmd -o \"$opts\""
-fi
-
-local first_run
-for host in $hosts; do
-    if [ -z "$first_run" ]; then
-        \tmux new-session -d -s ${session_name} "$ssh_cmd $host $action"
-        first_run=true
-    else
-        \tmux split-window -t ${session_name} "$ssh_cmd $host $action"
-        \tmux select-layout -t ${session_name} tiled
-    fi
-done
-
-\tmux set-window-option -t ${session_name} synchronize-panes on
-\tmux attach-session -t ${session_name}
+### end of txssh
